name: CI
run-name: ${{ github.actor }} Pipeline PROCESSING 🚀
on:
  push:
    branches:
      - main

jobs:
  build-and-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
      
      - name: Lint
        run: npm run lint:js && npm run lint:css

      - name: Fix linting issues
        run: npm run lint-staged

      - name: Prettier
        run: npm run prettier
      
      - name: Test
        run: npm test

      - name: Build
        run: npm install && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages 
          folder: dist

      
